### ISSUE TITLE
Issue importing async function from decorators sript

### ISSUE THREAD

**Issue by SolvingCurves** [evereux/flicket#16]
Hello,
I've had the folowing issue while running "manage.py db init"
*python manage.py db init
...
from application.flicket.scripts.decorators import async
SyntaxError: invalid syntax*

By changing the name of the 'async' function' in the decorators.py script and in the email.py, no more issue: The function is now "def send_async_email(f)" in decorators.py and @send_async_email in email.py. 

I'm under Windows - python37 and using sqlite database.
It's working like a charm now and I've learned a lot in reading your code. thx.

**Comment by evereux** [comment]
Hello.

Interesting. I didn't have this error with my setup - Windows 10 and python 3.7 but I've no problem changing the function name to something more descriptive. I guess async clashes with something in python 3.7.

I've made this change to the 0.1.7 branch which I'll push into the main branch sometime soon.

Thanks for the feedback!

**Comment by evereux** [comment]
I'm not programmer professional or otherwise (the more I learn the more of a hack I feel) so feel free to talk nonsense. I'm a design engineer working in the aerospace industry. I started to learn python a couple of years ago and the small company I was at working desperately needed some kind of ticket system. I really didn't like those open source options I found. So, I created Flicket in my own time to improve my python skills.

With regards to attachments that's something you need to configure in Apache. Basically you'll need to map the flicket url for uploads to the folder in which the uploads live so it's apache that serves the files (python does it for you in development environment). If you can't get it working I'll post a sample of my apache config file. Not sure what the FAQ file problem is but I'll have a think on that ...

The facility for the user to select a language was one I'd considered for sometime and was going to do if there was enough interest. You're interested, that's enough for me. So, I've implemented flask-babel and it works. I'll do the upfront donkey work (shouldn't take long now I've got the concept working) and if you then could provide the french translation that would be awesome! Should be ready in day or so. I'll post back here when I've done that.

**Comment by evereux** [comment]
I've merged everything into the main branch now.

The file [messages.po](https://github.com/evereux/flicket/blob/master/application/translations/fr/LC_MESSAGES/messages.po) in `application/translations/fr/LC_MESSAGES/` is used by babel to compile for Flicket to use. If you look at the updated README you can see some instructions on how to do this.

If you manage to update the `messages.po` file with the french translations please do submit a pull request and I'll merge them into Flicket. It'd be great if you could. 👍 

Now, when an admin creates a new user the users locale can be selected. The user can also select the locale within their profile. If there are any strings I've missed let me know.

**Comment by SolvingCurves** [comment]
Nice !
I’ll translate this week and pull the French translation.
Thanks again !

De : evereux <notifications@github.com>
Envoyé : dimanche 13 janvier 2019 14:57
À : evereux/flicket <flicket@noreply.github.com>
Cc : SolvingCurves <christophe.callais@outlook.com>; Author <author@noreply.github.com>
Objet : Re: [evereux/flicket] Issue importing async function from decorators sript (#16)


I've merged everything into the main branch now.

The file messages.po<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fevereux%2Fflicket%2Fblob%2Fmaster%2Fapplication%2Ftranslations%2Ffr%2FLC_MESSAGES%2Fmessages.po&data=02%7C01%7C%7C06c5b97b49d842306af508d6795f0a37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636829846423863843&sdata=w46Vw%2BdHMkFFAkinibk0ESqgjJCESOd04%2FoBxsH43M0%3D&reserved=0> in application/translations/fr/LC_MESSAGES/ is used by babel to compile for Flicket to use. If you look at the updated README you can see some instructions on how to do this.

If you manage to update the messages.po file with the french translations please do submit a pull request and I'll merge them into Flicket. It'd be great if you could. 👍

Now, when an admin creates a new user the users locale can be selected. The user can also select the locale within their profile. If there are any strings I've missed let me know.

**Comment by evereux** [comment]
Closing ticket as the original question was resolved.
