### ISSUE TITLE
add time registration?

### ISSUE THREAD

**Issue by anielk** [evereux/flicket#23]
is it possible to add time registration, like worked time?

**Comment by evereux** [comment]
My immediate thought is not at the moment as I'd like to finish the API and finally get some documentation together. 

Unless, it's something you'd like to implement? How do you envisage this working?

**Comment by evereux** [comment]
I've been thinking about this. I was thinking maybe adding a field on ticket creation to add a value for estimated hours to complete. Then, on ticket completion / closure have a field to enter for actual time taken.

These hours can be totalled and shown on the departments / categories page.

Thoughts?

**Comment by xdml** [comment]
Hi, I just started to use flicket and if I it will be on me, I prefer to have possibility to add spent hours on every ticket update.

Personally I am thinking to do time records and to have possibility to record expected costs and expected income or bid and later to update real costs and real income with the real spent time, so I can later analyze if my bids and expected costs are good or not.

But it is because of my business I do. Definitely I will try to implement something like I briefly described, if I select flicket as my ticketing system.

**Comment by evereux** [comment]
I'm going to implement this this week.

**Comment by evereux** [comment]
I've now added this feature to the 0.2.1 branch: https://github.com/evereux/flicket/commit/f798f3fad923d014a0439c783f80378bee173eba

**Comment by anielk** [comment]
I going to test how this works, thanks!

**Comment by evereux** [comment]
Closing this ticket as request has been fulfilled, albeit simply, and have had no further feedback.
